name: SimpleHardcoreMode
version: '${version}'

main: org.raul.plugins.simpleHardcoreMode.SimpleHardcoreMode
api-version: '1.16'
author: "Latrell (Raul Reyes)"

commands:
  lives:
    permission: SimpleHardcoreMode.permission.lives
    permission-message: "You don not have enough privileges to use this command"
    description: "Manage player's lives"
    usage: "How to use it: /lives [get | set | add | defaultLives] [player] [amount]"

permissions:
  SimpleHardcoreMode.permission.lives:
    default: true
  SimpleHardcoreMode.permission.lives.admin:
    default: op